### ISSUE TITLE
Sending a Mail to all Teachers

### ISSUE THREAD

**Issue by SaifAlDilaimi** [thm-projects/arsnova-backend#42]
Hello,

at our university we have to delete all session that have not been used for 6 months (semester). Before we do that we would like to inform those that created the session to export it if they would like to keep it. How can we do that?

**Comment by dgerhardt** [comment]
There is no support in ARSnova to send an e-mail to all users since the application only knows about the addresses if database authentication is used.

To send a mail to users registered with ARSnova you could extend the backend and reuse the methods used to send registration mails.

For LDAP-based authentication ARSnova does not know about e-mail addresses (except LDAP configurations where the address is used as UID). You would need to query the LDAP server for mail addresses.

**Comment by SaifAlDilaimi** [comment]
Well thx for the answer @dgerhardt 

Is it possible to query the backend for all teachers uid?  We can use that also as mail adress..  how can I do that?

**Comment by dgerhardt** [comment]
Have a look at the following code:
https://github.com/thm-projects/arsnova-backend/blob/v2.4.2/src/main/java/de/thm/arsnova/dao/CouchDBDao.java#L1267-L1272

You might be able to reuse this to implement your use case.

**Comment by SaifAlDilaimi** [comment]
Can I query the couchdb directly for the information? As I wrote before we have also to delete the sessions that are 6 months old..

**Comment by dgerhardt** [comment]
Yes, you could write your own (temp) view, filter by `type === 'session'` and emit `lastOwnerActivity` and `creator` properties. I suggest, you have a look at the view `statistics/unique_session_creators` as an example.
