### ISSUE TITLE
Proposal: Implement Custom OpenIdProvider Authentication

### ISSUE THREAD

**Issue by glatzert** [thm-projects/arsnova-backend#66]
We'd like to use ARSNova with our own OpenIdConnect Server, which is currently not possible.
Since there's already Twitter, Facebook and Google AuthN, this should be not to complex to implement.

If you do not have the time to implement it yourself, we'd also volunteer one of our employees in early february to implement it.

**Comment by dgerhardt** [comment]
We have planned to support OIDC authentication in the next major release 3.0 but there is no release date at this time. Due to framework updates and architectural changes it would be hard to share the code between both versions so we will not implement it for 2.x anymore.

If you want to implement OIDC authentication for version 2.x you could use the pac4j library which is used by ARSnova to allow authentication via Google & Co.

http://www.pac4j.org/docs/clients/openid-connect.html

**Comment by glatzert** [comment]
If we implement it into the 2.x source base, are you willing to accept that as PR?
Our faculty for physics, informatics and mathematics would like to use ARS, but due to the choice of login methods, we currently cannot.

Besides not having a release date - do you have a rough timeframe?

**Comment by dgerhardt** [comment]
We would be happy to accept a merge request. If there are any implementation related questions, we can use this issue to discuss them.

> Besides not having a release date - do you have a rough timeframe?

Sometime in the second half of 2019. We plan to have multiple beta releases and start using the new backend on our own servers before the final release.

**Comment by dgerhardt** [comment]
Since we he had to adjust our Google authentication code for 2.7, we decided to move the OIDC implementation in our release schedule. Version 2.7 was released last week and includes generic OIDC support. Our current implementation requires the server to support configuration discovery.

https://github.com/thm-projects/arsnova-backend/releases/tag/v2.7.0

**Comment by glatzert** [comment]
Well - than we'll try to use it. Thank you! 👍
