### ISSUE TITLE
Missing file for project setup

### ISSUE THREAD

**Issue by eXsiLe95** [thm-projects/arsnova-backend#70]
According to the developer instructions to get your project running, you need to copy the ARSnova configuration file to set up your couchdb. The file located at `src/main/resources/arsnova.properties.example` however is missing.

![image](https://user-images.githubusercontent.com/31202904/67877941-cc8d5480-fb3a-11e9-89b3-0aa44fe222cc.png)

**Comment by commana** [comment]
Hi @eXsiLe95,

Thanks for reporting this. Our documentation is geared towards the stable releases, the most current is 2.7.3 at this moment. You'll find the mentioned file there.

If you want to work on the master branch, the new configuration behavior is as follows:

1. Copy file src/main/resources/config/**defaults.yml** to /etc/arsanova/**application.yml** (note the different file names; the folder to copy to is free for your choosing, see step 3. below)
2. Make changes to  `application.yml` according to your needs, eg. adjust CouchDB settings
3. Start `arsnova-backend` with the parameter `-D arsnova.config-dir=/etc/arsnova`

I am going to update the documentation so that this is clear. :+1:

**Comment by commana** [comment]
Fixed via 1110b2c421ef2b194441c9002d5e0fef66d29723.
